Repository LikeLion13-Blog-Project/frontend, pull requests merged in 2025-05, with the labels that each got.

#7 feat: add header and list components for home page
  .gitignore
  index.html
  package-lock.json
  package.json
  src/components/Home/HeaderSection.jsx
  src/components/Home/ListItem.jsx
  src/components/Home/ListSection.jsx
  src/components/Home/data.js
  src/pages/Home.jsx
  src/utils/dateFormat.js
  vite.config.js
Labels: feature✨, HTML&CSS🎨

#12 Backend/post write/UI markup
  src/components/WritePost/ContentSection.jsx
  src/components/WritePost/TitleSection.jsx
  src/components/WritePost/WriteButton.jsx
  src/components/WritePost/WriterSection.jsx
  src/pages/WritePost.jsx
Labels: feature✨, HTML&CSS🎨

#14 Home/UI markup#5
  public/Logo.svg
  public/vite.svg
  src/App.jsx
  src/Router.jsx
  src/assets/fonts/PretendardVariable.woff2
  src/components/Home/.gitkeep
  src/components/Home/ListItem.jsx
  src/components/PostDetail/.gitkeep
  src/components/PostDetail/CommentDeleteBtn.jsx
  src/components/PostDetail/LikeBtn.jsx
  src/components/PostDetail/PostCommentList.jsx
  src/components/PostDetail/PostContent.jsx
  src/components/PostDetail/PostWriteComment.jsx
  src/components/PostDetail/mockData.js
  src/components/WritePost/.gitkeep
  src/components/common/Header.jsx
  src/components/common/Layout.jsx
  src/components/common/LoginButton.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/PostDetail.jsx
  src/styles/GlobalStyles.js
  src/styles/font.css
Labels: HTML&CSS🎨

#16 댓글 생성 error 처리
  src/components/PostDetail/CommentDeleteBtn.jsx
  src/components/PostDetail/PostCommentList.jsx
  src/components/PostDetail/PostWriteComment.jsx
  src/pages/PostDetail.jsx
Labels: feature✨, HTML&CSS🎨, bugfix🐞

#10 `Post Detail` 컨텐츠와 좋아요 섹션 구현 완료
  .gitignore
  src/pages/Home.jsx
Labels: feature✨, HTML&CSS🎨
